# Generated by Django 3.0.8 on 2020-07-16 14:58

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_athelete_practice_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athelete',
            name='training_plan',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
