# Generated by Django 3.0.8 on 2020-07-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200716_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athelete',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
