# Generated by Django 3.0.8 on 2020-07-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200716_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athelete',
            name='profile_pic',
            field=models.ImageField(default='new_face.jpg', upload_to='profile_pics'),
        ),
    ]
