# Generated by Django 3.0.8 on 2020-07-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200716_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='athelete',
            name='sport',
            field=models.CharField(choices=[('Road Cycling', 'CYC'), ('Mountain Biking', 'MTB'), ('Trail Running', 'TR'), ('Road Running', 'RR'), ('Swimming', 'SWM'), ('Pilates', 'PLT'), ('Stretching', 'STR')], default='Stretches', max_length=16),
        ),
    ]
