# Generated by Django 3.0.8 on 2020-07-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_athelete_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athelete',
            name='sport',
            field=models.CharField(choices=[('CYC', 'Road Cycling'), ('MTB', 'Mountain Biking'), ('TRR', 'Trail Running'), ('RDR', 'Road Running'), ('SWM', 'Swimming'), ('PLT', 'Pilates'), ('STR', 'Stretching')], default='Stretches', max_length=16),
        ),
    ]
