# Generated by Django 3.0.8 on 2020-07-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_kb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
