# Generated by Django 3.0.8 on 2020-07-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200716_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REC', 'Recovery'), ('TRN', 'Training')], default='Training', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='athelete',
            name='sport',
            field=models.CharField(choices=[('CYC', 'Road Cycling'), ('MTB', 'Mountain Biking'), ('TRR', 'Trail Running'), ('RDR', 'Road Running'), ('SWM', 'Swimming'), ('PLT', 'Pilates'), ('STR', 'Stretching')], default='Stretching', max_length=16),
        ),
    ]
