# Generated by Django 3.0.8 on 2020-07-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200717_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athelete',
            name='training_plan',
        ),
    ]
