# Generated by Django 3.0.8 on 2020-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_athelete_training_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='fri',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='fri_d',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='mon',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='mon_d',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='sat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='sat_d',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='sun',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='sun_d',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='thu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='thu_d',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='tue',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='tue_d',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='wed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='wed_d',
            field=models.TextField(null=True),
        ),
    ]
