# Generated by Django 3.0.8 on 2020-07-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200717_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='fri_d',
            new_name='Friday_Description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='fri',
            new_name='Friday_Title',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='mon_d',
            new_name='Monday_Description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='mon',
            new_name='Monday_Title',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='sat_d',
            new_name='Saturday_Description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='sat',
            new_name='Saturday_Title',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='sun_d',
            new_name='Sunday_Description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='sun',
            new_name='Sunday_Title',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='thu_d',
            new_name='Thursday_Description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='thu',
            new_name='Thursday_Title',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='tue_d',
            new_name='Tuesday_Description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='tue',
            new_name='Tuesday_Title',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='wed_d',
            new_name='Wednesday_Description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='wed',
            new_name='Wednesday_Title',
        ),
    ]
