# Generated by Django 3.0.8 on 2020-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200717_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('REC', 'Recovery'), ('TRN', 'Training')], default='Training', max_length=10, null=True),
        ),
    ]
