# Generated by Django 3.0.8 on 2020-07-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200717_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Friday_Video_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='Monday_Video_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='Saturday_Video_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='Sunday_Video_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='Thursday_Video_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='Tuesday_Video_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='Wednesday_Video_url',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
