# Generated by Django 3.0.8 on 2020-07-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200717_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Sunday_Video_url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
