# Generated by Django 3.0.8 on 2020-07-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20200717_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Sunday_Video_url',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
