# Generated by Django 3.0.8 on 2020-07-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20200717_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kb',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
