# Generated by Django 3.0.8 on 2020-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20200717_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='practice',
            field=models.CharField(max_length=100),
        ),
    ]
