# Generated by Django 3.0.8 on 2020-07-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_kb_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athelete',
            name='training_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.plan'),
        ),
    ]
